### ISSUE TITLE
how to change the default device 

### ISSUE THREAD

**Issue by Maple-geekZhu** [hkchengrex/Tracking-Anything-with-DEVA#119]
I didn't expect use the model in default 'cuda'(device:0)(because there is other programs work in it, it will cause OOM error) , I want use it in other GPU device(such as 'cuda:2'), how to change it?
I have tried directly change the device in grounding_dino.py and inference.py
(1)grounding_dino.py
    gd_model = GroundingDINOModel(model_config_path=GROUNDING_DINO_CONFIG_PATH,
                                  model_checkpoint_path=GROUNDING_DINO_CHECKPOINT_PATH,
                                  device='cuda:2')
(2)inference.py
  def load_model(model_config_path: str, model_checkpoint_path: str, device: str = "cuda"):
      args = SLConfig.fromfile(model_config_path)
      args.device = 'cuda:2'
      model = build_model(args)
      checkpoint = torch.load(model_checkpoint_path, map_location="cpu")
      model.load_state_dict(clean_state_dict(checkpoint["model"]), strict=False)
      model.eval()
      return model
But it didn't work

**Comment by Maple-geekZhu** [comment]
When I change the code "    gd_model, sam_model = get_grounding_dino_model(cfg, 'cuda:2')" in demo_with_text.py, it cause error:
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling cublasLtMatmul with transpose_mat1 1 transpose_mat2 0 m 256 n 20906 k 1024 mat1_ld 1024 mat2_ld 1024 result_ld 256 abcType 2 computeType 68 scaleType 0
but if I use the default 'cuda', the error disappear(as I mentioned below, there will be a OMM error because other programs are running)

**Comment by hkchengrex** [comment]
You don't need to change the code. You can specify CUDA_VISIBLE_DEVICES. See https://stackoverflow.com/questions/39649102/how-do-i-select-which-gpu-to-run-a-job-on

**Comment by Maple-geekZhu** [comment]
thanks, it works, I forgot to try this simple configuration.
